"""Execute every fenced python block in docs/.

The documentation described an API that had drifted from the code for a long
time: arguments in the wrong order, a tolerance default given as 0.05 where the
source said 0.025, and three functions documented under names that never
existed. Signatures are now generated by mkdocstrings so they cannot drift, but
prose examples still can -- unless something runs them.
"""

import pathlib
import re
import subprocess
import sys
import textwrap

import pytest

ROOT = pathlib.Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
#: fences may be indented when nested inside a markdown list item, which is
#: valid markdown and needs dedenting before the block will compile
FENCE = re.compile(r"^([ \t]*)```python\n(.*?)^\1```", re.S | re.M)


def python_blocks(page: pathlib.Path) -> list[str]:
    return [textwrap.dedent(body) for _indent, body in FENCE.findall(page.read_text())]


#: README.md is included verbatim by docs/index.md, so it is the published
#: homepage and its examples must run like any other page's.
PAGES = sorted(p for p in [*DOCS.glob("*.md"), ROOT / "README.md"] if python_blocks(p))


@pytest.mark.parametrize("page", PAGES, ids=lambda p: p.name)
def test_page_examples_run(page):
    """Blocks are concatenated in document order, as a reader would follow them.

    That also catches an example depending on a name defined further down the
    page, which is how two of these were broken.
    """
    code = "\n".join(python_blocks(page))
    result = subprocess.run(
        [sys.executable, "-c", code], capture_output=True, text=True, timeout=600
    )
    assert (
        result.returncode == 0
    ), f"{page.name} examples failed:\n{result.stderr.strip()[-1500:]}"


def test_every_page_with_code_uses_a_python_fence():
    """An untagged fence is not executed, so it can rot unnoticed."""
    offenders = []
    for page in sorted([*DOCS.glob("*.md"), ROOT / "README.md"]):
        text = page.read_text()
        for match in re.finditer(r"```(\w*)\n(.*?)```", text, re.S):
            lang, body = match.group(1), match.group(2)
            if lang:
                continue
            looks_like_python = re.search(
                r"^\s*(from |import |with |[A-Za-z_]\w*\s*=\s*\w+\()", body, re.M
            )
            if looks_like_python:
                line = text[: match.start()].count("\n") + 1
                offenders.append(f"{page.name}:{line}")
    assert not offenders, f"untagged python blocks are never executed: {offenders}"
